import type { Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import { GraduationCap } from 'lucide-react'
import './globals.css'
import Link from 'next/link'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Exam Buddy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-between items-center p-4 gap-4 h-16 border-b border-gray-200">
            {/* App Title/Logo */}
            <div className="flex items-center gap-3">
              <div className="bg-gradient-to-r from-[#6c47ff] to-[#9c88ff] p-2 rounded-xl shadow-lg">
                <GraduationCap className="w-6 h-6 text-white" />
              </div>
              <h1 className="text-xl sm:text-2xl font-bold bg-gradient-to-r from-[#6c47ff] to-[#9c88ff] bg-clip-text text-transparent">
                <Link href="/">Exam Buddy</Link>
              </h1>
            </div>

            {/* Authentication Buttons */}
            <div className="flex items-center gap-4">
            {/* Authentication Buttons */}
            <div className="flex items-center gap-4">
              {/* Show sign-in/sign-up buttons when user is not logged in */}
              <SignedOut>
                <SignInButton>
                  <button className="border border-gray-300 text-gray-700 rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer hover:bg-gray-50 transition-colors">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer hover:bg-[#5a3dd8] transition-colors">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
            </div>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}